// import 'dart:convert';
//
// import 'package:flutter/services.dart';
// import 'package:fpdart/fpdart.dart';
// import 'package:hashlib/hashlib.dart';
// import 'package:hivez_flutter/hivez_flutter.dart';
// import 'package:json_repair_flutter/json_repair_flutter.dart';
import 'package:tarot_again/util/util.dart';

part 'asset_storage_rep.freezed.dart';

/// [AssetStorageRep] is a data class (generated by freezed, without toJson/fromJson)
/// Each instance requires the hash ([assetHash]) of the [assetString], the [hashDate]
/// on which the hash was generated, and the boolean flag [userOverride] to indicate
/// whether the asset is from the original asset bundle, or has been overriden
/// by user input (and therefore should be kept in preference to the asset version,
/// even if the asset version has been updated since this override was made).
@Freezed(fromJson: false, toJson: false)
abstract class AssetStorageRep with _$AssetStorageRep {
  factory AssetStorageRep({
    required String assetKey,
    required String assetHash,
    required String assetString,
    required DateTime hashDate,
    required bool userOverride,
  }) = _AssetStorageRep;
}
