import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:fpdart/fpdart.dart';
import 'package:hashlib/hashlib.dart';
import 'package:hivez_flutter/hivez_flutter.dart';
import 'package:json_repair_flutter/json_repair_flutter.dart';
import 'package:tarot_again/util/util.dart';

export 'types.dart';

typedef JsonMap = IMap<String, dynamic>;

/// [AssetStorageRep] is a data class (generated by freezed, without toJson/fromJson)
/// Each instance requires the hash ([assetHash]) of the [assetString], the [hashDate]
/// on which the hash was generated, and the boolean flag [userOverride] to indicate
/// whether the asset is from the original asset bundle, or has been overriden
/// by user input (and therefore should be kept in preference to the asset version,
/// even if the assetversion has been updated since this override was made).
// @Freezed(fromJson: false, toJson: false)
// abstract class AssetStorageRep with _$AssetStorageRep {
//   factory AssetStorageRep({
//     required String assetKey,
//     required String assetHash,
//     required String assetString,
//     required DateTime hashDate,
//     required bool userOverride,
//   }) = _AssetStorageRep;
// }

@singleton
class AssetManager with Logging {
  AssetManager(this.appSettings, this.hiveService) {
    verbose("AssetManager.AssetManager()");
  }

  final AppSettings appSettings;
  final HiveService hiveService;

  late final Box<String, AssetStorageRep> stringAssetsBox;

  /// [createBoxes] is called during the service [create] function, below. It
  /// makes sure that the boxes we use to strong string assets and their file
  /// hashes are set up and ready to use.
  Future<void> createBoxes() async {
    /// This function gets called during the service [create] function, below.
    ///
    stringAssetsBox = await hiveService.ensureBox<AssetStorageRep>(
      "stringAssetsBox",
    );
  }

  @FactoryMethod(preResolve: true)
  static Future<AssetManager> create(
    HiveService hiveService,
    AppSettings appSettings,
  ) async {
    Logging.staticVerbose('AssetManager.create');
    Logging.staticVerbose('  HiveService is $hiveService');
    Logging.staticVerbose('  AppSettings is $appSettings');
    AssetManager retVal = AssetManager(appSettings, hiveService);

    await retVal.createBoxes();

    Logging.staticVerbose('  awaiting getAllAssetPaths');
    final assetPaths = await getAllAssetPaths();

    Logging.staticVerbose('  awaiting fetchLayouts');
    final layoutsByName = await retVal.fetchLayouts();

    // initialize all of our fixed assets, here, in one go
    Logging.staticVerbose('  batching for SignalsManager');
    batch(() {
      SignalsManager.allAssetPaths.value = assetPaths;
      SignalsManager.tarotLayoutsByName.value = layoutsByName;
    });
    Logging.staticVerbose('  finished AssetManager.create()');
    return retVal;
  }

  static Future<Iterable<String>> getAllAssetPaths() async {
    log("AssetManager.getAllAssetPaths");
    AssetManifest? assetManifest;
    var assetPaths = <String>[];

    try {
      assetManifest = await AssetManifest.loadFromAssetBundle(rootBundle);
      log("  assetManifest is $assetManifest");
      assetPaths = assetManifest.listAssets();
    } catch (e, s) {
      log("  loadFromAssetBundle raised error $e");
      assetPaths = [e.toString(), s.toString()];
    }

    return assetPaths;
  }

  TaskEither<FlutterError, String> _loadTarotLayoutsJson() =>
      TaskEither<FlutterError, String>.tryCatch(() async {
        return await rootBundle.loadString("assets/tarotLayouts.json");
      }, (e, s) => e as FlutterError);

  Either<FormatException, JsonMap> _parseTarotLayoutsJson(String json) =>
      Either<FormatException, JsonMap>.tryCatch(
        () => IMap<String, dynamic>(jsonDecode(json)),
        (e, s) => e as FormatException,
      );

  /// [loadStringAsset] accepts two parameters - an asset path, and a
  /// key in the Settings Hive store for storing the hash of the asset.
  /// It returns a Future<Either<Object, String>>. The return value is a Future
  /// because assets are loaded asynchronously. The left branch of the either will
  /// be any exception raised during this process; the right branch is simply the
  /// string value of the asset, whether it's loaded from Hive or from the assets
  /// bundle.
  Future<Either<Object, String>> loadStringAsset(
    String assetPath,
    String assetKeyName,
  ) async {
    Either<Object, String> retVal = Left("");

    try {
      String assetAsString = await rootBundle.loadString(assetPath);
      String assetHash = sha3_512sum(assetAsString);

      // on a first run, this value will be null and that's fine.
      String? storedHash = Settings.getValue<String>(assetKeyName);

      if (storedHash != assetHash) {
        Settings.setValue(assetKeyName, assetHash);
        retVal = Right(assetAsString);
      }
    } catch (e, _) {
      retVal = Left(e);
    }

    return retVal;
  }

  Future<IMap<String, TarotLayout>> fetchLayouts() async {
    /// This function loads a json file at assets/tarotLayouts.json that describes all of the different
    /// tarotLayouts available, captured as a single object where each key represents a different pascalCase layout name
    /// and the contents of each key are a json-encoded TarotLayout.  This is simple to read and the function
    /// requires no inputs to achieve its results.
    verbose("LayoutProvider.fetchLayouts");

    // adding new functionality:
    // what I want to do is check to see if the version of tarotLayouts.json on
    // disk is *newer* than the json layouts stored in hive.
    // A way to do that, I think, is to compare hashes of the asset on disk with
    // a hash stored in the Settings object; if they differ, then:
    //   convert the layout json file to objects, as usual
    //   save the objects to hive and set the hash stored in Settings to the new
    //   hash.
    verbose("  getting hash of layouts file");

    IMap<String, TarotLayout> retVal = const IMap<String, TarotLayout>.empty();

    final existingLayoutsBox = await hiveService.ensureBox('tarotLayoutsBox');

    String layoutsJson = await rootBundle.loadString(
      "assets/tarotLayouts.json",
    );

    verbose("  layoutsJson is $layoutsJson");
    final layoutJsonHash = sha3_512sum(layoutsJson);
    verbose("  layoutJsonHash is $layoutJsonHash");

    final oldHash = Settings.getValue<String>("tarotLayoutsHash");
    verbose("  oldHash is $oldHash");

    if (oldHash != layoutJsonHash) {
      if (layoutsJson.isNotEmpty) {
        verbose("  trying repairJson");
        final decodedData = repairJson(
          layoutsJson,
          logging: true,
          skipDecodeAttempt: true,
        );
        verbose("  repairJson returned $decodedData");

        final LayoutList? allLayouts;

        verbose("  trying LayoutList.fromJson()");
        try {
          allLayouts = LayoutList.fromJson(decodedData['data']);
          verbose("  success! allLayouts is $allLayouts");
          verbose("  converting to map");

          for (var item in allLayouts.layouts) {
            retVal = retVal.add(item.name, item);
          }

          verbose('  retVal has keys: ${retVal.keys}');

          final bock = retVal.unlock;
          verbose(' retVal.unlock has runtime type ${bock.runtimeType}');

          await existingLayoutsBox.putAll(retVal.unlock);
        } catch (e, _) {
          error("  Failure! LayoutList.fromJson raised error $e");
        }
      } else {
        verbose("  importing existing layouts from hive box 'tarotLayouts");
        verbose("  existingLayoutsBox is $existingLayoutsBox");

        // a box is essentially a map, and this map is going to have the type
        // Map<String, TarotLayout> - as that is the way it was created!
        retVal =
            ((await existingLayoutsBox.toMap()) as Map<String, TarotLayout>)
                .lock;
      }
    }

    // close the box, deallocate the resources, etc. etc.
    await existingLayoutsBox.closeBox();

    return retVal;
  }

  Future<Option<String>> loadMarkdownAsset(String assetPath) async =>
      TaskOption<String>.tryCatch(
        () async => await rootBundle.loadString(assetPath),
      ).run();

  Future<Option<String>> tryLoadMarkdownAsset(
    Iterable<String> assetPaths,
    String kind,
  ) async {
    return assetPaths
        .where((asset) => assetKind(asset) == kind)
        .firstOrNull
        .letWithElse(
          (asset) => loadMarkdownAsset(asset),
          orElse: Option<String>.none(),
        );
  }

  Option<AssetGenImage> tryImageAsset(
    Iterable<String> assetPaths,
    String kind,
  ) => assetPaths
      .where((asset) => assetKind(asset) == kind)
      .firstOrNull
      .letWithElse(
        (assetPath) => Option<AssetGenImage>.of(AssetGenImage(assetPath)),
        orElse: Option<AssetGenImage>.none(),
      );

  String assetKind(String assetPath) =>
      assetPath.split("/").let((it) => it[it.length - 2]);

  Future<TCModelAssets> loadAssetsForCard(TarotDeckCards card) async {
    log("AssetProvider.loadAssetsForCard");

    if (card == TarotDeckCards.noneCard) {
      return (
        description: Option<String>.none(),
        uprightMeaning: Option<String>.none(),
        reversedMeaning: Option<String>.none(),
        image: Option<AssetGenImage>.none(),
      );
    }

    return ComputedsManager.deckAssetPaths.value
        .where((String assetName) => assetName.contains(card.name))
        .let(
          (cardAssets) async => switch (cardAssets.isEmpty) {
            true => (
              description: Option<String>.none(),
              uprightMeaning: Option<String>.none(),
              reversedMeaning: Option<String>.none(),
              image: Option<AssetGenImage>.none(),
            ),
            false => (
              description: await tryLoadMarkdownAsset(
                cardAssets,
                "descriptions",
              ),
              uprightMeaning: await tryLoadMarkdownAsset(
                cardAssets,
                "uprightMeanings",
              ),
              reversedMeaning: await tryLoadMarkdownAsset(
                cardAssets,
                "reversedMeanings",
              ),
              image: tryImageAsset(cardAssets, "images"),
            ),
          },
        );
  }
}
