import 'package:flutter/services.dart';
import 'package:fpdart/fpdart.dart';
// import 'package:hashlib/hashlib.dart';
import 'package:hivez_flutter/hivez_flutter.dart';
import 'package:json_repair_flutter/json_repair_flutter.dart';
import 'package:tarot_again/util/util.dart';
// import 'package:rust/rust.dart' show Result, Ok, Err;
// import 'package:exception_templates/exception_templates.dart';

export 'types.dart';

typedef JsonMap = IMap<String, dynamic>;

typedef AssetManagerReturn<R> = TaskEither<ExceptionOf<AssetManager>, R>;

/// [AssetStorageRep] is a data class (generated by freezed, without toJson/fromJson)
/// Each instance requires the hash ([assetHash]) of the [assetString], the [hashDate]
/// on which the hash was generated, and the boolean flag [userOverride] to indicate
/// whether the asset is from the original asset bundle, or has been overriden
/// by user input (and therefore should be kept in preference to the asset version,
/// even if the assetversion has been updated since this override was made).
// @Freezed(fromJson: false, toJson: false)
// abstract class AssetStorageRep with _$AssetStorageRep {
//   factory AssetStorageRep({
//     required String assetKey,
//     required String assetHash,
//     required String assetString,
//     required DateTime hashDate,
//     required bool userOverride,
//   }) = _AssetStorageRep;
// }

/// This class exists as a gateway to all assets bundled with this app.
/// It is a singleton, and all of its methods are static.
///
/// On creation, it sets some of the signals on [SignalManager] so that the values don't have to be
/// awaited on, and can just be read as Signals.
@singleton
class AssetManager(
  final HiveService hiveService,
  final SignalsManager signalsManager,
  final ComputedsManager computedsManager,
  final BoxInterface<String, String> assetPathHashBox,
) with Logging {
  @FactoryMethod(preResolve: true)
  static Future<AssetManager> create(
    HiveService hiveService,
    SignalsManager signalsManager,
    ComputedsManager computedsManager,
    // AppSettings appSettings,
  ) async {
    final BoxInterface<String, String> assetPathHashBox = await hiveService
        .ensureBox(
          "assetPathHashBox",
          options: BoxConfig("assetPathHashBox", logger: Logging.sDebug),
        );

    AssetManager retVal = AssetManager(
      hiveService,
      signalsManager,
      computedsManager,
      assetPathHashBox,
    );

    await retVal.getAndSetAllAssetPaths();
    await retVal.fetchAndSetLayouts();

    return retVal;
  }

  // static Future<Iterable<String>> getAllAssetPaths() async {
  Future<Unit> getAndSetAllAssetPaths() async {
    final paths = await AssetManifest.loadFromAssetBundle(rootBundle);

    signalsManager.allAssetPaths.value = paths.listAssets() as Iterable<String>;

    return unit;
  }

  /// [loadStringAsset] accepts two parameters - an asset path, and a
  /// key in the Settings Hive store for storing the hash of the asset.
  /// It returns a Future< Either< Object, String>>. The return value is a Future
  /// because assets are loaded asynchronously. The left branch of the either will
  /// be any exception raised during this process; the right branch is simply the
  /// string value of the asset, whether it's loaded from Hive or from the assets
  /// bundle.
  TaskOption<String> loadStringAsset(
    String assetPath,
    // String assetKeyName,
  ) => TaskOption<String>.tryCatch(
    () async => await rootBundle.loadString(assetPath),
  );

  /// [fetchAndSetLayouts] loads a json file at assets/tarotLayouts.json that describes all of the different
  /// tarotLayouts available, captured as a single object where each key represents a different pascalCase layout name
  /// and the contents of each key are a json-encoded TarotLayout.  This is simple to read and the function
  /// requires no inputs to achieve its results.
  ///
  /// The outcome of this is that, if the layouts can be fetched and parsed successfully, the SignalsManager signals
  /// tarotLayoutsByName and tarotLayouts will be set to the new values.  If the layouts cannot be fetched or parsed, the existing values will remain unchanged.
  Future<Unit> fetchAndSetLayouts() async {
    final updateSignals = action((
      IList<TarotLayout> ll,
      IMap<String, TarotLayout> mm,
    ) {
      signalsManager.tarotLayoutsByName.value = mm;
      signalsManager.tarotLayouts.value = ll;
    });

    final layoutsJson = await loadStringAsset("assets/tarotLayouts.json").run();

    layoutsJson.flatMap((layoutsJson) {
      if (layoutsJson.isNotEmpty) {
        IMap<String, TarotLayout> layoutsMap =
            const IMap<String, TarotLayout>.empty();

        final decodedData = repairJson(
          layoutsJson,
          logging: true,
          skipDecodeAttempt: true,
        );

        IList<TarotLayout> allLayouts = const IList<TarotLayout>.empty();

        try {
          allLayouts = IList<TarotLayout>(
            LayoutList.fromJson(decodedData['data']).layouts,
          );

          for (var item in allLayouts) {
            layoutsMap = layoutsMap.add(item.name, item);
          }
        } catch (e) {
          rethrow;
        }

        updateSignals(allLayouts, layoutsMap);
      }

      return Option<Unit>.of(unit);
    });

    return unit;
  }

  Future<Option<String>> loadMarkdownAsset(String assetPath) async {
    verbose("loadMarkdownAssets: assetPath is '$assetPath'");
    return TaskOption<String>.tryCatch(
      () async => await rootBundle.loadString("assets/$assetPath"),
    ).run();
  }

  Future<Option<String>> tryLoadMarkdownAsset(
    Iterable<String> assetPaths,
    String kind,
  ) async {
    return assetPaths
        .where((asset) => assetKind(asset) == kind)
        .firstOrNull
        .letWithElse(
          (asset) => loadMarkdownAsset(asset),
          orElse: Option<String>
              .none, // Option.none is a constructor; orElse needs a callable.
        );
  }

  Option<AssetGenImage> tryImageAsset(
    Iterable<String> assetPaths,
    String kind,
  ) => assetPaths
      .where((asset) => assetKind(asset) == kind)
      .firstOrNull
      .letWithElse(
        (assetPath) => Option<AssetGenImage>.of(AssetGenImage(assetPath)),
        orElse: Option<AssetGenImage>
            .none, // Option.none is a constructor; orElse needs a callable.
      );

  String assetKind(String assetPath) =>
      assetPath.split("/").let((it) => it[it.length - 2]);

  Future<TCModelAssets> loadAssetsForCard(TarotDeckCards card) async {
    // log("AssetProvider.loadAssetsForCard");

    if (card == TarotDeckCards.noneCard) {
      return (
        description: Option<String>.none(),
        uprightMeaning: Option<String>.none(),
        reversedMeaning: Option<String>.none(),
        image: Option<AssetGenImage>.none(),
      );
    }

    return computedsManager.deckAssetPaths.value
        .where((String assetName) => assetName.contains(card.name))
        .let(
          (cardAssets) async => switch (cardAssets.isEmpty) {
            true => (
              description: Option<String>.none(),
              uprightMeaning: Option<String>.none(),
              reversedMeaning: Option<String>.none(),
              image: Option<AssetGenImage>.none(),
            ),
            false => (
              description: await tryLoadMarkdownAsset(
                cardAssets,
                "descriptions",
              ),
              uprightMeaning: await tryLoadMarkdownAsset(
                cardAssets,
                "uprightMeanings",
              ),
              reversedMeaning: await tryLoadMarkdownAsset(
                cardAssets,
                "reversedMeanings",
              ),
              image: tryImageAsset(cardAssets, "images"),
            ),
          },
        );
  }
}
