import 'package:flutter/services.dart';
import 'package:fpdart/fpdart.dart';
import 'package:hashlib/hashlib.dart';
import 'package:hivez_flutter/hivez_flutter.dart';
import 'package:json_repair_flutter/json_repair_flutter.dart';
import 'package:tarot_again/util/util.dart';
// import 'package:rust/rust.dart' show Result, Ok, Err;
// import 'package:exception_templates/exception_templates.dart';

export 'types.dart';

typedef JsonMap = IMap<String, dynamic>;

typedef AssetManagerReturn<R> = TaskEither<ExceptionOf<AssetManager>, R>;

/// [AssetStorageRep] is a data class (generated by freezed, without toJson/fromJson)
/// Each instance requires the hash ([assetHash]) of the [assetString], the [hashDate]
/// on which the hash was generated, and the boolean flag [userOverride] to indicate
/// whether the asset is from the original asset bundle, or has been overriden
/// by user input (and therefore should be kept in preference to the asset version,
/// even if the assetversion has been updated since this override was made).
// @Freezed(fromJson: false, toJson: false)
// abstract class AssetStorageRep with _$AssetStorageRep {
//   factory AssetStorageRep({
//     required String assetKey,
//     required String assetHash,
//     required String assetString,
//     required DateTime hashDate,
//     required bool userOverride,
//   }) = _AssetStorageRep;
// }

@singleton
class AssetManager(
  final HiveService hiveService,
  final BoxInterface<String, String> assetPathHashBox,
) with Logging {
  @FactoryMethod(preResolve: true)
  static Future<AssetManager> create(
    HiveService hiveService,
    // AppSettings appSettings,
  ) async {
    final BoxInterface<String, String> assetPathHashBox = await hiveService
        .ensureBox(
          "assetPathHashBox",
          options: BoxConfig("assetPathHashBox", logger: Logging.sDebug),
        );

    AssetManager retVal = AssetManager(hiveService, assetPathHashBox);

    // await retVal.createBoxes();

    // Logging.sVerbose('  awaiting getAllAssetPaths');
    final assetPaths = await getAllAssetPaths().run();

    // Logging.sVerbose('  awaiting fetchLayouts');
    final layoutsByName = await retVal.fetchLayouts();

    // initialize all of our fixed assets, here, in one go
    // Logging.sVerbose('  batching for SignalsManager');
    batch(() {
      assetPaths.flatMap((ap) {
        SignalsManager.allAssetPaths.value = ap;

        return Either<ExceptionOf<AssetManager>, Unit>.right(unit);
      });
      // SignalsManager.allAssetPaths.value = assetPaths;
      SignalsManager.tarotLayoutsByName.value = layoutsByName;
    });
    // Logging.sVerbose('  finished AssetManager.create()');
    return retVal;
  }

  // static Future<Iterable<String>> getAllAssetPaths() async {
  static AssetManagerReturn<Iterable<String>> getAllAssetPaths() =>
      TaskEither.tryCatch(
        () => AssetManifest.loadFromAssetBundle(rootBundle),
        (e, _) => ExceptionOf<AssetManager>(
          message: "loadFromAssetBundle raised an exception",
          invalidState: e,
          expectedState: "assetManifest = the asset manifest",
        ),
      ).flatMap(
        (AssetManifest assetManifest) =>
            AssetManagerReturn<Iterable<String>>.right(
              assetManifest.listAssets() as Iterable<String>,
            ),
      );

  // TaskEither<FlutterError, String> _loadTarotLayoutsJson() =>
  //     TaskEither<FlutterError, String>.tryCatch(() async {
  //       return await rootBundle.loadString("assets/tarotLayouts.json");
  //     }, (e, s) => e as FlutterError);
  //
  // Either<FormatException, JsonMap> _parseTarotLayoutsJson(String json) =>
  //     Either<FormatException, JsonMap>.tryCatch(
  //       () => IMap<String, dynamic>(jsonDecode(json)),
  //       (e, s) => e as FormatException,
  //     );

  /// [loadStringAsset] accepts two parameters - an asset path, and a
  /// key in the Settings Hive store for storing the hash of the asset.
  /// It returns a Future< Either< Object, String>>. The return value is a Future
  /// because assets are loaded asynchronously. The left branch of the either will
  /// be any exception raised during this process; the right branch is simply the
  /// string value of the asset, whether it's loaded from Hive or from the assets
  /// bundle.
  TaskEither<ExceptionOf<AssetManager>, String> loadStringAsset(
    String assetPath,
    String assetKeyName,
  ) {
    return AssetManagerReturn<String>.tryCatch(
      () => rootBundle.loadString(assetPath),
      (e, _) => ExceptionOf<AssetManager>(
        message: "Unable to load asset; assetPath is '$assetPath'",
        invalidState: e,
        expectedState: "a string",
      ),
    ).flatMap((s) {
      final String assetHash = sha3_512sum(s);
      return AssetManagerReturn<String>.right(s);
    });
    //   assetAsString
    // }, (e, _) => ExceptionOf<AssetManager>(
    //       message: "assetPath is '$assetPath'",
    //       invalidState: e,
    //       expectedState: "",
    //     ));
    // /// [retVal] is not read until the return statement at the end of this method.
    // /// Both paths through the try / catch block assign an appropriate value to retVal.
    // Result<String, ExceptionOf<AssetManager>> retVal;

    // try {
    //   String assetAsString = await rootBundle.loadString(assetPath);
    //   String assetHash = sha3_512sum(assetAsString);

    //   retVal = Ok(assetAsString);

    //   // on a first run, this value will be null and that's fine.
    //   // String? storedHash = Settings.getValue<String>(assetKeyName);

    //   // if (storedHash != assetHash) {
    //   //   Settings.setValue(assetKeyName, assetHash);
    //   //   retVal = Right(assetAsString);
    //   // }
    // } on Exception catch (e) {
    //   retVal = Err(
    //     ExceptionOf<AssetManager>(
    //       message: "assetPath is '$assetPath'",
    //       invalidState: e,
    //       expectedState: "",
    //     ),
    //   );
    // }

    // return retVal;
  }

  /// [fetchLayouts] loads a json file at assets/tarotLayouts.json that describes all of the different
  /// tarotLayouts available, captured as a single object where each key represents a different pascalCase layout name
  /// and the contents of each key are a json-encoded TarotLayout.  This is simple to read and the function
  /// requires no inputs to achieve its results.
  // verbose("LayoutProvider.fetchLayouts");
  Future<IMap<String, TarotLayout>> fetchLayouts() async {
    // adding new functionality:
    // what I want to do is check to see if the version of tarotLayouts.json on
    // disk is *newer* than the json layouts stored in hive.
    // A way to do that, I think, is to compare hashes of the asset on disk with
    // a hash stored in [hive]; if they differ, then:
    //   convert the layout json file to objects, as usual
    //   save the objects to hive and set the hash stored in Settings to the new
    //   hash.
    // verbose("  getting hash of layouts file");

    IMap<String, TarotLayout> retVal = const IMap<String, TarotLayout>.empty();

    // final existingLayoutsBox = await hiveService.ensureBox(
    //   'tarotLayoutsBox',
    //   options: BoxConfig('tarotLayouts'),
    // );

    String layoutsJson = await rootBundle.loadString(
      "assets/tarotLayouts.json",
    );

    // verbose("  layoutsJson is $layoutsJson");
    final layoutJsonHash = sha3_512sum(layoutsJson);
    // verbose("  layoutJsonHash is $layoutJsonHash");

    final oldHash = SignalsManager.tarotLayoutsHash.value;
    // verbose("  oldHash is $oldHash");

    if (oldHash != layoutJsonHash) {
      if (layoutsJson.isNotEmpty) {
        // verbose("  trying repairJson");
        final decodedData = repairJson(
          layoutsJson,
          logging: true,
          skipDecodeAttempt: true,
        );
        // verbose("  repairJson returned $decodedData");

        final LayoutList? allLayouts;

        // verbose("  trying LayoutList.fromJson()");
        try {
          allLayouts = LayoutList.fromJson(decodedData['data']);
          // verbose("  success! allLayouts is $allLayouts");
          // verbose("  converting to map");

          for (var item in allLayouts.layouts) {
            retVal = retVal.add(item.name, item);
          }

          // verbose('  retVal has keys: ${retVal.keys}');

          // final bock = retVal.unlock;
          // verbose(' retVal.unlock has runtime type ${bock.runtimeType}');

          SignalsManager.existingLayoutsBox.value = retVal.unlock;
        } catch (e) {
          error("  Failure! LayoutList.fromJson raised error $e");
        }
      } else {
        // verbose("  importing existing layouts from hive box 'tarotLayouts");

        retVal = SignalsManager.existingLayoutsBox.value
            .cast<String, TarotLayout>()
            .lock;
        // verbose("  existingLayoutsBox is $retVal");
      }
    }

    return retVal;
  }

  Future<Option<String>> loadMarkdownAsset(String assetPath) async {
    verbose("loadMarkdownAssets: assetPath is '$assetPath'");
    return TaskOption<String>.tryCatch(
      () async => await rootBundle.loadString("assets/$assetPath"),
    ).run();
  }

  Future<Option<String>> tryLoadMarkdownAsset(
    Iterable<String> assetPaths,
    String kind,
  ) async {
    return assetPaths
        .where((asset) => assetKind(asset) == kind)
        .firstOrNull
        .letWithElse(
          (asset) => loadMarkdownAsset(asset),
          orElse: Option<String>
              .none, // Option.none is a constructor; orElse needs a callable.
        );
  }

  Option<AssetGenImage> tryImageAsset(
    Iterable<String> assetPaths,
    String kind,
  ) => assetPaths
      .where((asset) => assetKind(asset) == kind)
      .firstOrNull
      .letWithElse(
        (assetPath) => Option<AssetGenImage>.of(AssetGenImage(assetPath)),
        orElse: Option<AssetGenImage>
            .none, // Option.none is a constructor; orElse needs a callable.
      );

  String assetKind(String assetPath) =>
      assetPath.split("/").let((it) => it[it.length - 2]);

  Future<TCModelAssets> loadAssetsForCard(TarotDeckCards card) async {
    // log("AssetProvider.loadAssetsForCard");

    if (card == TarotDeckCards.noneCard) {
      return (
        description: Option<String>.none(),
        uprightMeaning: Option<String>.none(),
        reversedMeaning: Option<String>.none(),
        image: Option<AssetGenImage>.none(),
      );
    }

    return ComputedsManager.deckAssetPaths.value
        .where((String assetName) => assetName.contains(card.name))
        .let(
          (cardAssets) async => switch (cardAssets.isEmpty) {
            true => (
              description: Option<String>.none(),
              uprightMeaning: Option<String>.none(),
              reversedMeaning: Option<String>.none(),
              image: Option<AssetGenImage>.none(),
            ),
            false => (
              description: await tryLoadMarkdownAsset(
                cardAssets,
                "descriptions",
              ),
              uprightMeaning: await tryLoadMarkdownAsset(
                cardAssets,
                "uprightMeanings",
              ),
              reversedMeaning: await tryLoadMarkdownAsset(
                cardAssets,
                "reversedMeanings",
              ),
              image: tryImageAsset(cardAssets, "images"),
            ),
          },
        );
  }
}
