import 'package:event_bus/event_bus.dart';
import 'package:flutter/widgets.dart';

import 'util.dart';

export "package:event_bus/event_bus.dart";

// typedef EventFilterFunction<EventType> = bool Function(EventType);

/// marker class for event receivers
interface class IEventReceiver {}

@module
abstract class EventBusModule {
  @singleton
  EventBus get eventBus => EventBus();
}

/// [EventBase] is the base class for all events in the app. Event data are
/// immutable.
@immutable
abstract class EventBase<T extends Object?> {
  /// EventBase can store a data object of any type, but is not required to
  final T? data;
  final IEventReceiver? replyTo; // if this event is the origin of a request
  // for a service, set replyTo to this. The generated response will include
  // the same value in replyTo.

  /// [EventBase] constructor with an optional sender (if the response should be
  /// addressed to the sender), and optional data of any type
  const EventBase({this.replyTo, this.data});

  /// once an event is created, using event.emit will send the event to the
  /// event bus; this getter returns the event.
  EventBase get emit => this.also((it) => sl<EventBus>().fire(it));
}

// class _EmptyEvent extends EventBase {}

typedef EventHandler<EventType extends EventBase> =
    void Function(EventType event);
typedef EventFilter<EventType extends EventBase> =
    bool Function(EventType event);

typedef SubscriptionMap<EventType extends EventBase> =
    IMap<EventType, StreamSubscription<EventType>>;

mixin EventReceiverMixin implements IEventReceiver {
  SubscriptionMap _subscriptionMap = const SubscriptionMap.empty();

  bool selfEventFilter<EventType extends EventBase>(EventType event) {
    return event.replyTo == this;
  }

  void setHandler<U extends EventBase>({
    required U eventType,
    required EventHandler<U> handler,
    EventFilter? filter,
  }) {
    final receiver = receiveEvents<U>(onData: handler, filter: filter);
    _subscriptionMap = _subscriptionMap.add(eventType, receiver);
    // subscriptionMap.add(U, ( receiveEvents(onData: handler)(event, receiveEvent) {
  }

  void cancelReceiver<U extends EventBase>(U eventType) {
    final StreamSubscription? receiver = _subscriptionMap[eventType];
    receiver?.cancel();
    _subscriptionMap = _subscriptionMap.remove(eventType);
  }

  void dispose() {
    _subscriptionMap.forEach((eventType, receiver) {
      receiver.cancel();
    });
    _subscriptionMap = const SubscriptionMap.empty();
  }
}

/// Here's an example of how to define an event class based on EventBase.
/// It's also possible to define local variables, and to override the data
/// getter.
/// For this example, the constructor parameters are just stored as a tuple.
/// [@immutable]
/// class TryoutEvent extends [EventBase]<(String, bool)> {
///   const TryoutEvent({required String name, required bool tryoutSucceeded})
///     : super((name, tryoutSucceeded));
/// }
///
/// and of course it's possible to define event sub-hierarchies based on [sealed]
/// classes and the like
/// @freezed
/// sealed class JumboEvents extends EventBase\<JumboEvents\> with _$JumboEvents  {
///   // this allows us to have the data getter in the code generated by freezed.
///   const JumboEvents._();
///
///   const factory JumboEvents.sprinkleEvent({
///     required String name,
///     required String sprinkleType,
///   }) = _SprinkleEvent;
///
///   const factory JumboEvents.showerEvent({
///     required String name,
///     required String showerType,
///   }) = _ShowerEvent;
///
///   factory JumboEvents.fromJson(Map\<String, dynamic\> json) =>
///       _$JumboEventsFromJson(json);
/// }

/// EventFilterFunction is the type of a function that takes an event of type T
/// and returns a boolean. It is used to filter events of a particular type T
/// on the EventBus by a predicate.

// final EventBus eventBus = EventBus();

// void createEventBus() {
//   if (!sl.isRegistered<EventBus>()) {
//     sl.registerSingleton<EventBus>(eventBus);
//   }
// }

// class InflateEvent<T> {}
//
// void createInflator<T extends Object>(T Function() createFunc) {
//   if (!sl.isRegistered<T>()) {
//     sl.registerLazySingleton<T>(() => createFunc());
//
//     eventBus.on<InflateEvent<T>>().listen((event) {
//       sl<T>();
//     });
//   }
// }

// sl is provided by the GetIt package, and is simply a reference to
// GetIt.I<T>();

// This variable is a handy way to make the event bus available globally, assuming
// that EventBus has been created and registered with GetIt previously.

// global functions that make it easy to use EventBus

Stream<T> getEventBusStream<T extends EventBase>([EventFilter? filter]) {
  // this global function does not rely on WatchIt for functionality.

  // Use this function to receive events of a particular type T from the event bus.
  // Optionally, filter those events with a function that returns true to emit the
  // event or false to drop the event.
  // To receive all events, don't supply a type T - event bus will give the
  // stream everything it receives.

  Stream<T> s = sl<EventBus>().on<T>();

  return filter != null ? s.where((T event) => filter(event)) : s;
}

StreamSubscription<T> receiveEvents<T extends EventBase>({
  // this global function does not rely on WatchIt for functionality.

  // supply a void handler function that takes an event of type T, optionally filters it
  // with a boolean function that also takes an event of type T, and passes
  // any events that come through the filter to the handler.
  // save the StreamSubscription returned by this function to have control over
  // the stream used, to close it for example.
  required EventHandler<T> onData,
  EventFilter? filter,
}) => getEventBusStream<T>(filter).listen(onData);

T awaitEvent<T extends EventBase<DataType>, DataType>(
  T initial, [
  EventFilter? filter,
]) {
  // this global function DOES rely on WatchIt for functionality.

  // this is useful for building widgets, among other things.  See the WatchIt
  // package for details on how that works for the watchStream function.

  // awaitEvent returns the data that was passed into the stream
  AsyncSnapshot<T> snapshot = AsyncSnapshot<T>.nothing();

  snapshot = watchStream<EventBus, T>(
    (_) => getEventBusStream<T>(filter),
    initialValue: initial,
  );

  return snapshot.data as T;
}

// [watchEvents] is useful
AsyncSnapshot<T> watchEvents<T extends EventBase>(
  T initial, [
  EventFilter? filter,
]) =>
    // this global function DOES rely on WatchIt for functionality
    watchStream<EventBus, T>(
      (EventBus item) => getEventBusStream<T>(filter),
      initialValue: initial,
    );
//
// typedef EventResponder<EventType extends EventBase<DataType>, DataType>(
//   StreamSubscription Function<EventType>(),
//   EventFilterFunction<EventType>(),
// );

/// Class EventObserver is a kinda-sorta bloc-like entity that allows one to
/// respond to one or more types of input events and generate zero or more
/// response events in return, plus perform any other needed changes.
// class EventObserver {
//   EventType initialEvent;
//   EventType? _currentEvent;
//   Iterable<EventType>? _respondEventTypes;
//
//   EventObserver({
//     required this.initialEvent,
//     Iterable<EventType>? respondEventTypes,
//   }) : _respondEventTypes = respondEventTypes;
//
//   EventType get current => (_currentEvent ?? initialEvent);
//   Object? get data => current.data;
//
//   Iterable<EventType>? get respondEventTypes => _respondEventTypes;
// }
